# Generated by Django 5.1.3 on 2024-12-04 13:54

import cloudinary.models
import djangoBestFootballCardCollectibles.accounts.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res-console.cloudinary.com/dgsoxzoz0/media_explorer_thumbnails/4a39cb1c9403cca560c66a67d23c7d86/detailed', max_length=255, null=True, validators=[djangoBestFootballCardCollectibles.accounts.validators.validate_profile_picture_size], verbose_name='image'),
        ),
    ]
