# Generated by Django 5.1.3 on 2024-12-04 14:01

import cloudinary.models
import djangoBestFootballCardCollectibles.accounts.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[djangoBestFootballCardCollectibles.accounts.validators.validate_profile_picture_size], verbose_name='image'),
        ),
    ]
